# Generated by Django 5.2.16 on 2026-07-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formy', '0002_alter_form_options_form_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
