# Generated by Django 5.2.16 on 2026-07-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formy', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('zh', 'Chinese')], default='en', max_length=8),
        ),
    ]
