# Generated by Django 5.2.16 on 2026-07-12 17:15

import django.db.models.deletion
import formy.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formy', '0005_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='form_banners/'),
        ),
        migrations.AddField(
            model_name='form',
            name='footer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='form',
            name='header_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to=formy.models.attachment_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='formy.formsubmission')),
            ],
        ),
    ]
