# Generated by Django 5.2.16 on 2026-07-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formy', '0006_form_banner_image_form_footer_text_form_header_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='allow_theme_toggle',
            field=models.BooleanField(default=False),
        ),
    ]
